easy_admin:
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'
            - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

    entities:
        BlogPost:
            class: App\Entity\BlogPost
            form:
                fields:
                    - title
                    - { property: 'content', type: 'fos_ckeditor' }
                    - categories
                    - tags

        Category:
            class: App\Entity\Category
            form:
                fields:
                    - name
                    - parent

        Tag:
            class: App\Entity\Tag
            form:
                fields:
                    - name
