easy_admin:
    entities:
        Category:
            class: App\Entity\Category
            form:
                title: 'Add customer'
                fields:
                    - name
                    - parent
