easy_admin:
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'

    entities:
        BlogPost:
            class: App\Entity\BlogPost
            form:
                fields:
                    - title
                    - slug
                    - public
                    - ogImage
                    - { property: 'language', type: 'choice', type_options: { choices: { 'Español': 'es', 'English': 'en' } } }
                    - { property: 'translations', type_options: { by_reference: false } }
                    - { property: 'abstract', type: 'code_editor', language: 'markdown' }
                    - { property: 'content', type: 'code_editor', language: 'markdown' }
                    - published
                    - created
                    - updated
                    - categories
                    - tags

        Image:
            class: App\Entity\Image
            list:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.admin_images%' }

            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.admin_images%' }

            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }

        Category:
            class: App\Entity\Category
            form:
                fields:
                    - name
                    - parent

        Tag:
            class: App\Entity\Tag
            form:
                fields:
                    - name

        User:
            class: App\Entity\User

        Invoice:
            class: App\Entity\Invoice