easy_admin:
    design:
        form_theme:
            - '@EasyAdmin/form/bootstrap_4.html.twig'

    entities:
        BlogPost:
            class: App\Entity\BlogPost
            form:
                fields:
                    - title
                    - public
                    - { property: 'content', type: 'code_editor', language: 'markdown' }
                    - categories
                    - tags

        Image:
            class: App\Entity\Image
            list:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.admin_images%' }

            show:
                fields:
                    - { property: 'image', type: 'image', base_path: '%app.path.admin_images%' }

            form:
                fields:
                    - { property: 'imageFile', type: 'vich_image' }

        Category:
            class: App\Entity\Category
            form:
                fields:
                    - name
                    - parent

        Tag:
            class: App\Entity\Tag
            form:
                fields:
                    - name
